site_name: Open Chat Studio Documentation
site_url: https://dimagi.github.io/open-chat-studio-docs/
theme:
  name: material
  features:
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
copyright: Copyright &copy; 2024 Dimagi

extra_css:
  - assets/extra.css

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Home: index.md
  - How-to Guides:
      - how-to/index.md
      - how-to/add_a_knowledge_base.md
      - how-to/remote_api.md
      - how-to/global_search.md
      - how-to/deploy_to_different_channels.md
      - how-to/configure_providers.md
      - how-to/api_access.md
      - how-to/setting_up_a_survey.md
  - Concepts:
      - concepts/index.md
      - Experiments:
        - concepts/experiment/index.md
        - concepts/llm.md
        - concepts/participant_data.md
        - concepts/prompt_variables.md
        - concepts/source_material.md
        - concepts/versioning.md
        - concepts/custom_actions.md
        - concepts/consent.md
        - concepts/channels.md
      - Pipelines:
        - concepts/pipelines/index.md
        - concepts/pipelines/nodes.md
        - concepts/pipelines/history.md
      - Team:
          - concepts/team/index.md
          - concepts/authentication-providers.md
          - concepts/messaging_providers.md
      - Assistants:
          - concepts/assistants.md
  - About: about.md
