name: Proofread PRs
on:
  pull_request_target:
    types:
      - opened

jobs:
  proofread:
    permissions: write-all
    runs-on: ubuntu-latest
    name: Proofread PRs
    steps:
      - name: Proofread PR
        uses: snopoke/proof-reader-ai@configure-action
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Required to write a PR review
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_MODEL: 'gpt-4o-mini'
          file-pattern: '\.md$'
          prompt-prefix: 'Your task is to review pull requests for the documentation of Open Chat Studio.'
